# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  maven: circleci/maven@0.0.12
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: mule		  
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_VERSION: 4.3.0
          MULE_APP_NAME: jenkins-demo-venky
          MULE_ENV: SANDBOX
          MULE_WORKER_TYP: MICRO
          MULE_WORKER: 1
    steps:
      - checkout
      - restore_cache:
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - save_cache:
          paths:
            - ~/.m2
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - run:
          name: Build
          command: |
            mvn clean compile -s settings.xml
      - run:
          name: mUnit Test
          command: |
            mvn clean test -s settings.xml
      - run:
          name: artifactory deployment
          command: |
            mvn clean deploy -s settings.xml
      - run:
          name: cloudhub deployment
          command: |
            mvn -s settings.xml clean deploy -DmuleDeploy
